[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py35', 'py36', 'py37', 'py38', 'py39']
include = 'docs/conf\.py|fiscalyear\.py|setup\.py|test_fiscal_year\.py'
