name: black
on:
  push:
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/black.yaml'
  pull_request:
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/black.yaml'
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Black
      run: pip3 install black
    - name: Run Black Checks
      run: black --check .
