name: style
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install black
      run: pip3 install black
    - name: Run black checks
      run: black --check --diff .
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install flake8
    - name: Run flake8 checks
      run: flake8
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install pip dependencies
      run: pip install isort[colors]
    - name: Run isort checks
      run: isort . --check --diff
